development: &non_production_settings
  airbrake: ''
  github:
    key: ''
    secret: ''
  sidekiq:
    user: ''
    password: ''

test:
  <<: *non_production_settings
  domain: test.host

production:
  <<: *non_production_settings
